In [113]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn import metrics
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.decomposition import PCA
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report
from sklearn.preprocessing import LabelEncoder 
from sklearn.preprocessing import MinMaxScaler

# Pre-processing

In [114]:
df=pd.read_csv('/content/drive/MyDrive/4th sem/PR-ML[3-0-2] - cmn/major project/diabetes_data.csv',sep=';')

df['gender'].replace(['Male', 'Female'],[0, 1], inplace=True)

In [115]:
pd.unique(df['gender'])

array([0, 1])

In [116]:
df.head()

age  gender  polyuria  polydipsia  sudden_weight_loss  weakness  \
0   40       0         0           1                   0         1   
1   58       0         0           0                   0         1   
2   41       0         1           0                   0         1   
3   45       0         0           0                   1         1   
4   60       0         1           1                   1         1   

   polyphagia  genital_thrush  visual_blurring  itching  irritability  \
0           0               0                0        1             0   
1           0               0                1        0             0   
2           1               0                0        1             0   
3           1               1                0        1             0   
4           1               0                1        1             1   

   delayed_healing  partial_paresis  muscle_stiffness  alopecia  obesity  \
0                1                0                 1         1        1   
1                0                1                 0         1        0   
2                1                0                 1         1        0   
3                1                0                 0         0        0   
4                1                1                 1         1        1   

   class  
0      1  
1      1  
2      1  
3      1  
4      1

In [117]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 520 entries, 0 to 519
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   age                 520 non-null    int64
 1   gender              520 non-null    int64
 2   polyuria            520 non-null    int64
 3   polydipsia          520 non-null    int64
 4   sudden_weight_loss  520 non-null    int64
 5   weakness            520 non-null    int64
 6   polyphagia          520 non-null    int64
 7   genital_thrush      520 non-null    int64
 8   visual_blurring     520 non-null    int64
 9   itching             520 non-null    int64
 10  irritability        520 non-null    int64
 11  delayed_healing     520 non-null    int64
 12  partial_paresis     520 non-null    int64
 13  muscle_stiffness    520 non-null    int64
 14  alopecia            520 non-null    int64
 15  obesity             520 non-null    int64
 16  class               520 non-null    int64
dt

#Train Test

In [118]:
# Choosing the features and the label
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

# train and test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [119]:
type(X_train)

pandas.core.frame.DataFrame

In [120]:
X_train = pd.DataFrame(X_train)
type(X_train)
# X_train.values
# type(X_train)

pandas.core.frame.DataFrame

In [121]:
encoder = MinMaxScaler()
X_train = encoder.fit_transform(X_train.values)
X_test = encoder.transform(X_test.values)


# # here i  wiil use flask

# import pickle

# pickle.dump(classifier_lr, open('model.pkl','wb'))

# # Loading model to compare the results
# model = pickle.load(open('model.pkl','rb'))


print(X_train)
print(X_test)

[[0.14864865 0.         0.         ... 0.         0.         0.        ]
 [0.41891892 0.         0.         ... 0.         0.         1.        ]
 [0.67567568 1.         1.         ... 1.         0.         0.        ]
 ...
 [0.72972973 0.         0.         ... 0.         1.         0.        ]
 [0.43243243 0.         1.         ... 0.         0.         0.        ]
 [0.64864865 0.         0.         ... 0.         0.         0.        ]]
[[0.68918919 0.         0.         ... 1.         1.         1.        ]
 [0.41891892 0.         1.         ... 1.         0.         0.        ]
 [0.36486486 1.         1.         ... 1.         0.         1.        ]
 ...
 [0.40540541 1.         1.         ... 1.         0.         0.        ]
 [0.43243243 1.         1.         ... 1.         1.         1.        ]
 [0.22972973 0.         0.         ... 0.         0.         0.        ]]


In [122]:
import pickle

pickle.dump(encoder, open('transform_data_of_array.pkl','wb'))

# Loading model to compare the results
transform_data_of_array = pickle.load(open('transform_data_of_array.pkl','rb'))

# Visualization

In [123]:
import seaborn as sns
import matplotlib.pyplot as plt

# sns.pairplot(df, hue='class', height=2)

# sns.scatterplot( x="polyuria",data=df,
#                 hue='class')
  
# # Placing Legend outside the Figure
# plt.legend(bbox_to_anchor=(1, 1), loc=2)
  
# plt.show()


In [124]:
type(X_train)

numpy.ndarray

# Data Prediction

In [125]:
# X_train = X_train.to_numpy()

# Logistic Regression
classifier_lr = LogisticRegression(random_state=0)
classifier_lr.fit(X_train, y_train.values)

lr_test_score = classifier_lr.score(X_test, y_test)


In [126]:
lr_test_score = classifier_lr.score(X_test, y_test)
lr_test_score

0.9519230769230769

In [127]:
print(classifier_lr.predict(X_test))
# print(y_test.array)
type(y_test)

[1 1 1 0 0 1 1 1 0 1 1 0 1 1 1 1 0 1 1 1 1 1 1 0 0 0 1 1 1 1 1 0 1 1 1 1 1
 0 1 1 1 0 1 0 0 1 1 0 1 0 1 0 1 0 1 0 1 1 1 1 0 0 1 0 1 0 1 0 1 1 0 0 1 1
 0 1 0 1 1 0 1 1 0 0 1 1 1 1 0 0 0 0 0 0 0 1 1 1 1 0 0 1 1 1]


pandas.core.series.Series

In [128]:
import pickle

pickle.dump(classifier_lr, open('model.pkl','wb'))

# Loading model to compare the results
model = pickle.load(open('model.pkl','rb'))
# print(model.predict([[2, 9, 6]]))



In [129]:
# let transform 4 row of dataset to check
# 0- male,1 - female
data_a = [30,1,1,0,1,1,1,0,0,0,0,1,0,0,0,0]
trans1 = transform_data_of_array.transform([data_a])
trans1

data_a = [60,0,1,1,1,1,1,0,1,1,1,1,1,1,1,1]
trans2 = transform_data_of_array.transform([data_a])
trans2

array([[0.59459459, 0.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 0.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        ]])

In [130]:
k1 = model.predict(trans1)
k1
# k2 = model.predict(trans2)
# k2

array([1])

In [1]:
for i in range(1,15):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
